### ISSUE TITLE
putArchive wrong

### ISSUE THREAD

**Issue by philjones88** [Seikho/dockerode-ts#1]
https://github.com/Seikho/dockerode-ts/blob/master/dockerode.d.ts#L170

Is according to dockerode-ts:

`putArchive(options: {}, callback: Callback<WritableStream>): void;`

But dockerode is:

`Container.prototype.putArchive = function(file, opts, callback) {`

https://github.com/apocas/dockerode/blob/master/lib/container.js#L573

The `file` argument is missing.

**Comment by Seikho** [comment]
Thanks.

Does [this fix](https://github.com/Seikho/dockerode-ts/blob/hotfix/add-file-property-to-putarchive/dockerode.d.ts#L171) appear to be correct?

**Comment by philjones88** [comment]
@Seikho yup, looks good! :shipit:

**Comment by Seikho** [comment]
Great! Published as `v0.3.0`
