### ISSUE TITLE
publish as @types/dockerode

### ISSUE THREAD

**Issue by oferh** [Seikho/dockerode-ts#6]
Hi @Seikho,

Great work, just wondering why did you publish it as a separate package and not as @types/dockerode?

**Comment by Seikho** [comment]
Thank you.

I have actually been intending to publish to DefinitelyTyped for a while. I just haven't had the time or motivation to. Now that it's being requested, I'll go and do it 😛 

I originally needed a quick solution and I don't really mind this pattern. It couples the package version and types together which can be an issue using @types/..., typings or tsd. Especially in this case with how quickly the Docker API moves and breaks.

**Comment by RLovelett** [comment]
Any news or update on this?

**Comment by Seikho** [comment]
Just got back from holiday. I'll submit a PR to DefinitelyTyped today or tomorrow.

**Comment by Seikho** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14187

**Comment by Seikho** [comment]
DT has merged the PR. `@types/dockerode` should be available soon if it isn't already.
